version: '3'
services:

  mongodb:
    image: mongo 
    ports:
      - "27017:27017"
    environment:
     # - MONGO_INITDB_ROOT_USERNAME=admin
     # - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=your-database-name
    volumes:
      - mymongo-data:/data/db


  postgres:
    image: postgres:15.4
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: db_1122
      POSTGRES_DB: database
      POSTGRES_USER: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

  web:
    depends_on: 
      - mongodb
      - postgres
      - redis
    links:
      - mongodb:mongodb
      - postgres:postgres
      - redis:redis
    build: .
    restart: always
    ports:
      - "80:80"

volumes:
  postgres_data:
  mymongo-data:
